version: '3.8'

services:
  melody-cure-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: melody-cure-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config/config.yaml:/app/config/config.yaml:ro
      - ./logs:/app/logs
    environment:
      - GIN_MODE=release
    networks:
      - melody-cure-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  melody-cure-network:
    driver: bridge