version: '3.8'

services:
  # 后端应用 - 使用 host 网络模式直接访问宿主机服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: melody_cure_backend_simple
    restart: always
    network_mode: "host"
    environment:
      # 使用服务器上的 MySQL
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_USER=melody_cure
      - DB_PASSWORD=your_mysql_password
      - DB_NAME=melody_cure
      # 使用服务器上的 Redis
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
      - REDIS_PASSWORD=your_redis_password
      - REDIS_DB=0
      # JWT 配置
      - JWT_SECRET=your_jwt_secret_key_here
      # 七牛云配置
      - QINIU_ACCESS_KEY=your_qiniu_access_key
      - QINIU_SECRET_KEY=your_qiniu_secret_key
      - QINIU_BUCKET=your_bucket_name
      - QINIU_DOMAIN=your_domain.com
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs