version: '3.8'

services:
  # 后端应用
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: melody_cure_backend_prod
    restart: always
    ports:
      - "8080:8080"
    environment:
      # 使用服务器上的 MySQL
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-melody_cure}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${DB_NAME:-melody_cure}
      # 使用服务器上的 Redis
      - REDIS_HOST=${REDIS_HOST:-localhost}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB:-0}
      # JWT 配置
      - JWT_SECRET=${JWT_SECRET}
      # 七牛云配置
      - QINIU_ACCESS_KEY=${QINIU_ACCESS_KEY}
      - QINIU_SECRET_KEY=${QINIU_SECRET_KEY}
      - QINIU_BUCKET=${QINIU_BUCKET}
      - QINIU_DOMAIN=${QINIU_DOMAIN}
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    networks:
      - melody_cure_network

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: melody_cure_nginx_prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
    networks:
      - melody_cure_network

networks:
  melody_cure_network:
    driver: bridge