# Melody Cure Backend 配置文件示例
# 复制此文件为 config.yaml 并修改相应配置

# 数据库配置
database:
  host: localhost
  port: 3306
  user: root
  password: 12345678
  dbname: melody_cure
  charset: utf8mb4
  parseTime: true
  loc: Local
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600  # 秒

# Redis 配置
redis:
  host: localhost
  port: 6379
  password: "12345678"
  db: 0
  poolSize: 10
  minIdleConns: 5

# JWT 配置
jwt:
  secretKey: "your_jwt_secret_key_here"
  expireTime: 86400  # 24小时，单位：秒

# 邮箱配置
email:
  smtpHost: smtp.gmail.com
  smtpPort: 587
  username: your_email@gmail.com
  password: your_email_password
  from: your_email@gmail.com

# 七牛云配置
qiniu:
  accessKey: "your_access_key"      # 七牛云AccessKey
  secretKey: "your_secret_key"      # 七牛云SecretKey
  bucket: "your_bucket_name"        # 存储空间名称
  domain: "your_domain.com"         # 绑定的域名
  zone: "z0"                        # 存储区域 (z0华东, z1华北, z2华南, na0北美, as0东南亚)
  useHttps: true                    # 是否使用HTTPS
  expires: 3600                     # token过期时间(秒)