db:
  host: localhost
  port: 3306
  username: root
  password: 12345678
  dbname: melody_cure
  charset: utf8mb4
  parseTime: true
  loc: Local

redis:
  host: localhost
  port: 6379
  password: "12345678"
  db: 0

JWT:
  secretKey: "xxx"

Email:
  email: "xxx@xxx"
  key: "xxx"

# 七牛云图床配置
qiniu:
  access_key: "your_access_key"      # 七牛云AccessKey
  secret_key: "your_secret_key"      # 七牛云SecretKey
  bucket: "your_bucket_name"         # 存储空间名称
  domain: "your_domain.com"          # 绑定的域名
  zone: "z0"                         # 存储区域 (z0华东, z1华北, z2华南, na0北美, as0东南亚)
  use_https: true                    # 是否使用HTTPS
  expires: 3600                      # token过期时间(秒)